(setq mdg-local-links
      '("\"http://fr.wikipedia.org/wiki/\\(Afrique\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Albert_Zafy\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Amphibiens_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Andrianampoinimerina\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Andry_Rajoelina\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antaifasy\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antaimoro_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antaisaka_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antakarana_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antambahoaka\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antananarivo\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antandroy_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Antanosy_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Bara_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Betsileo\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Betsimisaraka\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Bezanozano_(ethnie)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Clarisse_Ratsifandrihamanana\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Culture_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Didier_Ratsiraka\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Démographie_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Expédition_coloniale_Madagascar-Tonkin\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Faritany\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Faritra\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Faune_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Fianarantsoa\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Flore_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Georges_Andriamanantena\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Histoire_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Insurrection_malgache_de_1947\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Jacques_Rabemananjara\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Jean-Luc_Raharimanana\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Jean_Joseph_Rabearivelo\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Jean_Laborde\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Joseph_Gallieni\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Liste_des_espèces_d'oiseaux_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Mahafaly\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Mainty\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Majunga\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Malgache\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Marc_Ravalomanana\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Merina\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Michèle_Rakotoson\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Mouvement_démocratique_de_la_rénovation_malgache\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Palais_de_la_Reine_(Tananarive)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Parti_des_déshérités_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Philibert_Tsiranana\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Politique_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Province_de_Diego-Suarez\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Province_de_Fianarantsoa\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Province_de_Majunga\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Province_de_Tamatave\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Province_de_Tananarive\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Province_de_Tuléar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Radama_II\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Radama_Ier\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Ranavalona\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Ranavalona_II\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Ranavalona_III\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Rasoherina\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Richard_Ratsimandrava\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Royaume_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(République_démocratique_malgache\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Sakalava\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Sihanaka\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Subdivisions_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Tamatave\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Tanala\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Tananarive\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Tropique_du_Capricorne\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Tsimihety_(peuple)\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Vazimba\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Vezo\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(Villes_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(économie_de_Madagascar\\)\""
	"\"http://fr.wikipedia.org/wiki/\\(équateur_(ligne_équinoxiale)\\)\""
	))

(defun mdg-links-replace ()
  "Replace external wikipedia with links to local pages."
  (interactive)
  (let ((links mdg-local-links) link)
    (while (setq link (pop links))
      (goto-char (point-min))
      (while (re-search-forward link nil t)
	(replace-match 
	 (concat "\"" (match-string 1) ".html\"") t t nil)))))

